import Head from 'next/head';
import PageCards from '../app/component/screens/PageCards/PageCards';

const CardsPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageCards />
    </div>
  );
};

export default CardsPage;
