import Head from 'next/head';
import PageForm from '../app/component/screens/PageForm/PageForm';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageForm />
    </div>
  );
}
