import PageTranslator from '../app/component/screens/PageTranslator/PageTranslater';
import Head from 'next/head';

const TranslatorPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTranslator />
    </div>
  );
};

export default TranslatorPage;
